#!/bin/bash
set -e

echo "=========================================="
echo "DEPLOYING SNMPResult UNPACKING FIX"
echo "=========================================="
echo ""
echo "This fixes the critical bug where SNMPResult objects"
echo "were being unpacked as tuples, causing 0 interfaces"
echo "to be discovered."
echo ""

# Push to git
echo "Step 1: Pushing to git..."
git push origin main
echo "✅ Code pushed"
echo ""

# SSH commands - user will need to run these manually on production server
echo "=========================================="
echo "MANUAL DEPLOYMENT STEPS"
echo "=========================================="
echo ""
echo "Run these commands on the production server (wardops@10.30.25.46):"
echo ""
echo "# 1. Pull latest code"
echo "cd /home/wardops/ward-ops-credobank"
echo "git pull origin main"
echo ""
echo "# 2. Rebuild containers with new code"
echo "docker compose -f docker-compose.production-priority-queues.yml build worker-snmp worker-interface"
echo ""
echo "# 3. Restart workers"
echo "docker compose -f docker-compose.production-priority-queues.yml restart worker-snmp worker-interface"
echo ""
echo "# 4. Wait 10 seconds for workers to start"
echo "sleep 10"
echo ""
echo "# 5. Test interface discovery on 10.195.57.5"
echo "docker exec wardops-worker-snmp-prod python3 /app/test_discovery_full.py"
echo ""
echo "# 6. Verify interfaces in database"
echo "docker exec wardops-postgres-prod psql -U wardops -d wardops -c \\"
echo "  \"SELECT if_index, if_name, if_alias, isp_provider, interface_type, is_critical, status"
echo "   FROM device_interfaces"
echo "   WHERE device_id = (SELECT id FROM standalone_devices WHERE ip = '10.195.57.5')"
echo "   ORDER BY if_index;\""
echo ""
echo "# 7. Expected output: 3 ISP interfaces"
echo "#    - Magti_Internet (interfaces 4 and 15)"
echo "#    - Silknet_Internet (interface 5)"
echo ""
echo "=========================================="
echo "VERIFICATION"
echo "=========================================="
echo ""
echo "After running the above, you should see:"
echo "✅ 3 ISP interfaces discovered (Magti x2, Silknet x1)"
echo "✅ Interface types correctly classified"
echo "✅ is_critical flag set to true for ISP interfaces"
echo ""
echo "If you see 0 interfaces, check worker logs:"
echo "docker logs wardops-worker-snmp-prod | tail -100"
echo ""
