version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wardops-postgres-local
    environment:
      POSTGRES_USER: ward_admin
      POSTGRES_PASSWORD: ward_admin_password
      POSTGRES_DB: ward_ops
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ward_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: wardops-redis-local
    command: redis-server --requirepass redispass
    ports:
      - "6380:6379"
    volumes:
      - redis_data_local:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wardops-api-local
    environment:
      DATABASE_URL: postgresql://ward_admin:ward_admin_password@postgres:5432/ward_ops
      REDIS_URL: redis://:redispass@redis:6379/0
      DEFAULT_ADMIN_PASSWORD: admin123
      SECRET_KEY: local-dev-secret-key-change-in-production
      ENVIRONMENT: development
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wardops-worker-local
    environment:
      DATABASE_URL: postgresql://ward_admin:ward_admin_password@postgres:5432/ward_ops
      REDIS_URL: redis://:redispass@redis:6379/0
      SECRET_KEY: local-dev-secret-key-change-in-production
      ENVIRONMENT: development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
    command: celery -A celery_app worker --loglevel=info --concurrency=10

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wardops-beat-local
    environment:
      DATABASE_URL: postgresql://ward_admin:ward_admin_password@postgres:5432/ward_ops
      REDIS_URL: redis://:redispass@redis:6379/0
      SECRET_KEY: local-dev-secret-key-change-in-production
      ENVIRONMENT: development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
    command: celery -A celery_app beat --loglevel=info

volumes:
  postgres_data_local:
  redis_data_local:
