version: '3.8'

# Production Setup Running Locally
# This matches the production environment on 10.30.25.39

services:
  postgres:
    image: postgres:15-alpine
    container_name: wardops-postgres-prod
    environment:
      POSTGRES_USER: ward_admin
      POSTGRES_PASSWORD: ward_admin_password
      POSTGRES_DB: ward_ops
    ports:
      - "5433:5432"  # Changed from 5432 to avoid conflict with VMware
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ward_admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: wardops-redis-prod
    command: redis-server --requirepass redispass --appendonly yes
    ports:
      - "6380:6379"  # Changed from 6379 to avoid conflict with VMware
    volumes:
      - redis_prod_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: wardops-victoriametrics-prod
    ports:
      - "8428:8428"  # HTTP API for metrics storage
    volumes:
      - victoriametrics_prod_data:/victoria-metrics-data
    command:
      - '--storageDataPath=/victoria-metrics-data'
      - '--httpListenAddr=:8428'
      - '--retentionPeriod=12'  # 12 months retention for SNMP metrics
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wardops-api-prod
    environment:
      DATABASE_URL: postgresql://ward_admin:ward_admin_password@postgres:5432/ward_ops
      REDIS_URL: redis://:redispass@redis:6379/0
      VICTORIA_URL: http://victoriametrics:8428
      DEFAULT_ADMIN_PASSWORD: admin123
      SECRET_KEY: ${SECRET_KEY:-local-prod-test-secret-key-change-me}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-}
      ENVIRONMENT: production
      MONITORING_MODE: snmp_only
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      victoriametrics:
        condition: service_started
    volumes:
      - ./logs:/app/logs
      - api_prod_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wardops-worker-prod
    command: celery -A celery_app worker --loglevel=info --concurrency=60
    environment:
      DATABASE_URL: postgresql://ward_admin:ward_admin_password@postgres:5432/ward_ops
      REDIS_URL: redis://:redispass@redis:6379/0
      VICTORIA_URL: http://victoriametrics:8428
      SECRET_KEY: ${SECRET_KEY:-local-prod-test-secret-key-change-me}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-}
      ENVIRONMENT: production
      MONITORING_MODE: snmp_only
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      victoriametrics:
        condition: service_started
    volumes:
      - ./logs:/app/logs
      - celery_prod_data:/data
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wardops-beat-prod
    command: celery -A celery_app beat --loglevel=info
    environment:
      DATABASE_URL: postgresql://ward_admin:ward_admin_password@postgres:5432/ward_ops
      REDIS_URL: redis://:redispass@redis:6379/0
      SECRET_KEY: ${SECRET_KEY:-local-prod-test-secret-key-change-me}
      ENVIRONMENT: production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - beat_prod_data:/data
    restart: unless-stopped

volumes:
  postgres_prod_data:
  redis_prod_data:
  victoriametrics_prod_data:
  api_prod_data:
  celery_prod_data:
  beat_prod_data:
