version: '3.8'

services:
  # VictoriaMetrics - Time-series database for metrics
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: ward-victoriametrics
    ports:
      - "8428:8428"  # HTTP API
    volumes:
      - victoriametrics-data:/victoria-metrics-data
    command:
      - '--storageDataPath=/victoria-metrics-data'
      - '--httpListenAddr=:8428'
      - '--retentionPeriod=12'  # 12 months retention
    restart: unless-stopped
    networks:
      - ward-monitoring

  # Redis - Task queue for Celery
  redis:
    image: redis:7-alpine
    container_name: ward-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - ward-monitoring

  # Grafana - Metrics visualization (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: ward-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - ward-monitoring

volumes:
  victoriametrics-data:
  redis-data:
  grafana-data:

networks:
  ward-monitoring:
    driver: bridge
